version: "3"

services:
  backend:
    ports:
      - 8000:80
    build:
      context: .
    volumes:
      - ./app:/app/app
      - ./app.db:/app/app.db
      - ./scripts:/app/scripts
    command: ./scripts/run.sh 80
