version: '3'

services:
  backend:
    ports:
      - 8000:80
    build:
      context: .
    volumes:
      - ./app:/app/app:z
      - ./tests:/app/tests:z
      - ./alembic:/app/alembic:z
      - ./data:/app/data:z
      - ./scripts:/app/scripts:z
    command: ./scripts/run.sh 80
    environment:
      FORCE_LOGIN: ${FORCE_LOGIN}
