version: "3"

services:
  backend:
    ports:
      - 8000:80
    build:
      context: .
    volumes:
      - ./app:/app/app:z
      - ./app.db:/app/app.db:z
      - ./scripts:/app/scripts:z
    command: ./scripts/run.sh 80
