version: "3"

services:
  backend:
    ports:
      - 8000:80
    build:
      context: .
    volumes:
      - ./organia-server:/app/app
    command: uvicorn app:app --host 0.0.0.0 --port 80 --reload
