"""

Revision ID: 01ab41cae17a
Revises: 0a8dbaf23241
Create Date: 2022-12-04 03:13:31.538688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ab41cae17a'
down_revision = '0a8dbaf23241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
