"""

Revision ID: 0779b32bff9d
Revises: 66df4440a2e5
Create Date: 2022-12-05 14:51:53.068507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0779b32bff9d'
down_revision = '66df4440a2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
