"""

Revision ID: 12726c923d5c
Revises: ee036fd92cea
Create Date: 2022-12-02 20:04:45.574224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12726c923d5c'
down_revision = 'ee036fd92cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
