"""

Revision ID: 17ff04b23db6
Revises: 22b471f0fb62
Create Date: 2022-11-29 23:44:51.249320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ff04b23db6'
down_revision = '22b471f0fb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('donor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
