"""

Revision ID: 19e99aeb4237
Revises: 4d67fe9b6523
Create Date: 2022-11-16 11:05:40.683214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e99aeb4237'
down_revision = '4d67fe9b6523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
