"""

Revision ID: 22b471f0fb62
Revises: 166c118fe1e0
Create Date: 2022-11-29 17:21:00.194614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b471f0fb62'
down_revision = '166c118fe1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
