"""

Revision ID: 240fecc57ca2
Revises: 94e5c8ac23c8
Create Date: 2021-09-09 21:10:28.817442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240fecc57ca2'
down_revision = '94e5c8ac23c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
