"""

Revision ID: 2fdd13d3ddb4
Revises: 8c2b7b1b3dc0
Create Date: 2022-11-16 10:42:19.268349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdd13d3ddb4'
down_revision = '8c2b7b1b3dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
