"""Add phone number in hospitals

Revision ID: 35c1b85ed864
Revises: 5fbb967f3ee0
Create Date: 2022-04-11 20:00:31.405200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c1b85ed864'
down_revision = '5fbb967f3ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
