"""

Revision ID: 4282b0eb9bc9
Revises: 84ee2c9937ed
Create Date: 2022-12-04 22:33:43.063131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4282b0eb9bc9'
down_revision = '84ee2c9937ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
