"""add chats and messages

Revision ID: 4336639178dd
Revises: 2c4d1baa13d0
Create Date: 2021-10-21 22:58:12.499361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4336639178dd'
down_revision = '2c4d1baa13d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_table('chat_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_groups_chat_id_chats')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_groups_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_groups'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_messages_chat_id_chats')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_hospitals_city_id_cities'), 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hospitals_city_id_cities'), type_='foreignkey')

    op.drop_table('messages')
    op.drop_table('chat_groups')
    op.drop_table('chats')
    # ### end Alembic commands ###
