"""Add kidney model and move variables from listing to it

Revision ID: 460be9b84314
Revises: 5f30590f5c74
Create Date: 2022-09-17 22:26:53.668990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460be9b84314'
down_revision = '5f30590f5c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('isRetransplantation')
        batch_op.drop_column('isDialyse')
        batch_op.drop_column('ARFDate')
        batch_op.drop_column('DateTransplantation')
        batch_op.drop_column('EndDateDialyse')
        batch_op.drop_column('startDateDialyse')
        batch_op.drop_column('ReRegistrationDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ReRegistrationDate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('startDateDialyse', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('EndDateDialyse', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('DateTransplantation', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('ARFDate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('isDialyse', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('isRetransplantation', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
