"""

Revision ID: 466eea5664aa
Revises: 41cee5a0cdea
Create Date: 2022-12-04 22:23:14.812722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466eea5664aa'
down_revision = '41cee5a0cdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
