"""

Revision ID: 4781da2f8f6c
Revises: 240fecc57ca2
Create Date: 2021-09-09 21:12:03.477978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4781da2f8f6c'
down_revision = '240fecc57ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
