"""

Revision ID: 4d67fe9b6523
Revises: f4428fa0ae13
Create Date: 2022-11-16 11:02:40.801530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d67fe9b6523'
down_revision = 'f4428fa0ae13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
