"""

Revision ID: 56f27cbf2540
Revises: 98b6261c65ae
Create Date: 2021-09-09 11:51:53.921039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f27cbf2540'
down_revision = '98b6261c65ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_manage_persons', sa.Boolean(), nullable=False),
    sa.Column('can_manage_roles', sa.Boolean(), nullable=False),
    sa.Column('can_manage_hospitals', sa.Boolean(), nullable=False),
    sa.Column('can_invite', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
