"""add lungs model

Revision ID: 5c8fd35ee8f2
Revises: 5f30590f5c74
Create Date: 2022-07-16 12:37:40.375164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8fd35ee8f2'
down_revision = '5f30590f5c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lungs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis_group', sa.String(), nullable=True),
    sa.Column('detailed_diagnosis', sa.String(), nullable=True),
    sa.Column('body_mass_index', sa.Float(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('assistance_required', sa.Boolean(), nullable=True),
    sa.Column('FVC_percentage', sa.Float(), nullable=True),
    sa.Column('PA_systolic', sa.Float(), nullable=True),
    sa.Column('oxygen_requirement', sa.Float(), nullable=True),
    sa.Column('six_minutes_walk_distance_over_150_feet', sa.Boolean(), nullable=True),
    sa.Column('continuous_mech_ventilation', sa.Boolean(), nullable=True),
    sa.Column('PCO2', sa.Float(), nullable=True),
    sa.Column('PCO2_increase_superior_to_15_percent', sa.Boolean(), nullable=True),
    sa.Column('age_at_transplant', sa.Integer(), nullable=True),
    sa.Column('creatinine_at_transplant', sa.Float(), nullable=True),
    sa.Column('ADL_required', sa.Boolean(), nullable=True),
    sa.Column('PCW_over_20_mmHg', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_lungs_listing_id_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lungs'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.drop_table('lungs')
    # ### end Alembic commands ###
