"""Add table for kidney score calculation

Revision ID: 5f30590f5c74
Revises: d59b3e678183
Create Date: 2022-08-07 19:42:19.041611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f30590f5c74'
down_revision = 'd59b3e678183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kidneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('isDialyse', sa.Boolean(), nullable=True),
    sa.Column('isRetransplantation', sa.Boolean(), nullable=True),
    sa.Column('startDateDialyse', sa.Date(), nullable=True),
    sa.Column('EndDateDialyse', sa.Date(), nullable=True),
    sa.Column('ARFDate', sa.Date(), nullable=True),
    sa.Column('DateTransplantation', sa.Date(), nullable=True),
    sa.Column('ReRegistrationDate', sa.Date(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_kidneys_listing_id_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kidneys'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.drop_table('kidneys')
    # ### end Alembic commands ###
