"""fix listings

Revision ID: 5fbb967f3ee0
Revises: bbd75567551b
Create Date: 2022-04-08 20:22:38.635483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbb967f3ee0'
down_revision = 'bbd75567551b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tumors_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('biggest_tumor_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alpha_fetoprotein', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('isDialyse', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isRetransplantation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('startDateDialyse', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('EndDateDialyse', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ARFDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('DateTransplantation', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ReRegistrationDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('A', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('B', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DR', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DQ', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('DQ')
        batch_op.drop_column('DR')
        batch_op.drop_column('B')
        batch_op.drop_column('A')
        batch_op.drop_column('ReRegistrationDate')
        batch_op.drop_column('DateTransplantation')
        batch_op.drop_column('ARFDate')
        batch_op.drop_column('EndDateDialyse')
        batch_op.drop_column('startDateDialyse')
        batch_op.drop_column('isRetransplantation')
        batch_op.drop_column('isDialyse')
        batch_op.drop_column('alpha_fetoprotein')
        batch_op.drop_column('biggest_tumor_size')
        batch_op.drop_column('tumors_number')

    # ### end Alembic commands ###
