"""

Revision ID: 60691e2362ef
Revises: 92972b80f279
Create Date: 2022-11-28 22:30:27.927572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60691e2362ef'
down_revision = '92972b80f279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
