"""add hospitals and cities

Revision ID: 6684f1a16849
Revises: 42f5f79ec850
Create Date: 2021-10-10 22:06:59.310979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6684f1a16849'
down_revision = '42f5f79ec850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('department_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities'))
    )
    op.drop_table('invitations')
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('city_id')

    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('consumer_id', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], name='fk_invitations_consumer_id_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_invitations_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_invitations')
    )
    op.drop_table('cities')
    # ### end Alembic commands ###
