"""Initial migration

Revision ID: 66df4440a2e5
Revises: 
Create Date: 2022-12-05 14:51:44.303988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66df4440a2e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
