"""

Revision ID: 6732c81a0410
Revises: 03009024dadf
Create Date: 2022-11-16 14:30:16.746986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6732c81a0410'
down_revision = '03009024dadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
