"""

Revision ID: 74b098e16833
Revises: 4781da2f8f6c
Create Date: 2021-09-09 21:34:42.302814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b098e16833'
down_revision = '4781da2f8f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
