"""

Revision ID: 76347c914d59
Revises: 9bfbb7fd1e63
Create Date: 2022-11-18 13:53:23.636857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76347c914d59'
down_revision = '9bfbb7fd1e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
