"""invitations

Revision ID: 76f8e4541d52
Revises: bbd75567551b
Create Date: 2022-03-17 05:52:47.479438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f8e4541d52'
down_revision = 'bbd75567551b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.Column('consumer_id', sa.Integer(), nullable=True),
        sa.Column('value', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_invitations_author_id_users')),
        sa.ForeignKeyConstraint(['consumer_id'], ['users.id'], name=op.f('fk_invitations_consumer_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###
