"""

Revision ID: 7d495cc21d28
Revises: 19e99aeb4237
Create Date: 2022-11-16 12:36:33.241082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d495cc21d28'
down_revision = '19e99aeb4237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heart_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tailleD', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('poidsD', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ABOD', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sexD', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('BNP_AVI', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PBN_AVI', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('DIA_AVI', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('CRE_AVI', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('BILI_AVI', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('TTLGP', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ICAR', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('F_ICAR', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comp_ad_std', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comp_ad_XPCA', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comp_ped_std', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comp_ped_XPCP', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_CCB', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('F1_DifAge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('F2_ABO', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('F3_SC', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('F4_SurvPostGRF', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('score_CCP', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_NACG', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('D_D_NAI', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('D_PREL', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.drop_column('poidsr')
        batch_op.drop_column('sexR')
        batch_op.drop_column('ABO_R')
        batch_op.drop_column('tailler')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heart_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tailler', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('ABO_R', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sexR', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('poidsr', sa.FLOAT(), nullable=True))
        batch_op.drop_column('score')
        batch_op.drop_column('D_PREL')
        batch_op.drop_column('D_D_NAI')
        batch_op.drop_column('score_NACG')
        batch_op.drop_column('score_CCP')
        batch_op.drop_column('F4_SurvPostGRF')
        batch_op.drop_column('F3_SC')
        batch_op.drop_column('F2_ABO')
        batch_op.drop_column('F1_DifAge')
        batch_op.drop_column('score_CCB')
        batch_op.drop_column('comp_ped_XPCP')
        batch_op.drop_column('comp_ped_std')
        batch_op.drop_column('comp_ad_XPCA')
        batch_op.drop_column('comp_ad_std')
        batch_op.drop_column('F_ICAR')
        batch_op.drop_column('ICAR')
        batch_op.drop_column('TTLGP')
        batch_op.drop_column('BILI_AVI')
        batch_op.drop_column('CRE_AVI')
        batch_op.drop_column('DIA_AVI')
        batch_op.drop_column('PBN_AVI')
        batch_op.drop_column('BNP_AVI')
        batch_op.drop_column('sexD')
        batch_op.drop_column('ABOD')
        batch_op.drop_column('poidsD')
        batch_op.drop_column('tailleD')

    # ### end Alembic commands ###
