"""

Revision ID: 817d5a59a833
Revises: 8c85c0e2c702
Create Date: 2022-12-04 21:49:09.055939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817d5a59a833'
down_revision = '8c85c0e2c702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
