"""

Revision ID: 874da5d09ec1
Revises: 56f27cbf2540
Create Date: 2021-09-09 11:53:49.427945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874da5d09ec1'
down_revision = '56f27cbf2540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
