"""

Revision ID: 8c2b7b1b3dc0
Revises: cdb56be9d498
Create Date: 2022-11-16 10:41:47.623078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2b7b1b3dc0'
down_revision = 'cdb56be9d498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
