"""

Revision ID: 93fd7e6e2deb
Revises: 24aefa994e54
Create Date: 2022-12-04 21:49:28.327701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fd7e6e2deb'
down_revision = '24aefa994e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
