"""

Revision ID: 98b6261c65ae
Revises: 5ddee5dcec24
Create Date: 2021-09-09 11:46:40.821477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b6261c65ae'
down_revision = '5ddee5dcec24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
