"""

Revision ID: 9bfbb7fd1e63
Revises: dfc780a36dda
Create Date: 2022-11-16 17:42:08.591383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfbb7fd1e63'
down_revision = 'dfc780a36dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
