"""Add donor/receivers

Revision ID: 9cb8915cecc7
Revises: 19d6140d7e2c
Create Date: 2021-06-11 00:00:50.241504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb8915cecc7'
down_revision = '19d6140d7e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
        batch_op.add_column(sa.Column('abo', sa.Enum('A', 'B', 'AB', 'O', name='abo'), nullable=True))
        batch_op.add_column(sa.Column('rhesus', sa.Enum('POSITIVE', 'NEGATIVE', name='rhesus'), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_persons_user_id'), ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_persons_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('supervisor_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_persons_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_persons_user_id'), type_='unique')
        batch_op.drop_column('rhesus')
        batch_op.drop_column('abo')
        batch_op.drop_column('gender')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
