"""

Revision ID: 9f8ca3a5aa5c
Revises: fb9d4f288cba
Create Date: 2022-12-05 20:48:49.467462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8ca3a5aa5c'
down_revision = 'fb9d4f288cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
