"""add heart model

Revision ID: a41613c7dfeb
Revises: 8fab142c9ea8
Create Date: 2022-09-18 21:09:29.678370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41613c7dfeb'
down_revision = '8fab142c9ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heart_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('R_D_NAI', sa.Date(), nullable=True),
    sa.Column('D_INSC', sa.Date(), nullable=True),
    sa.Column('tailler', sa.Float(), nullable=True),
    sa.Column('poidsr', sa.Float(), nullable=True),
    sa.Column('urgence', sa.Enum('XPCA', 'XPCP1', 'XPCP2', 'NA', name='urgence'), nullable=True),
    sa.Column('d_urgence', sa.Date(), nullable=True),
    sa.Column('KXPC', sa.String(), nullable=True),
    sa.Column('XPC', sa.String(), nullable=True),
    sa.Column('DRG', sa.Boolean(), nullable=True),
    sa.Column('CEC', sa.Boolean(), nullable=True),
    sa.Column('DCEC', sa.Date(), nullable=True),
    sa.Column('SIAV', sa.String(), nullable=True),
    sa.Column('CAT', sa.String(), nullable=True),
    sa.Column('BNP', sa.Integer(), nullable=True),
    sa.Column('DBNP', sa.Integer(), nullable=True),
    sa.Column('PROBNP', sa.Float(), nullable=True),
    sa.Column('DPROBNP', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_heart_scores_listing_id_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_heart_scores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heart_scores')
    # ### end Alembic commands ###
