"""

Revision ID: b06fd4083864
Revises: 2ad236ebc348
Create Date: 2022-12-03 15:48:00.952031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06fd4083864'
down_revision = '2ad236ebc348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
