"""Add fields required for lungs calculations

Revision ID: b3222c8fb91d
Revises: 1a602216162c
Create Date: 2022-03-15 23:28:01.052582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3222c8fb91d'
down_revision = '1a602216162c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tumors_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('biggest_tumor_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alpha_fetoprotein', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('isDialyse', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isRetransplantation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('startDateDialyse', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('EndDateDialyse', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ARFDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('DateTransplantation', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ReRegistrationDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('A', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('B', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DR', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DQ', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_mass_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('diabetes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('functional_status_assistance_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('FVC_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PA_systolic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('oxygen_requirement', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('six_minute_walk_distance_over_150_feet', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('continuous_mechanical_ventilation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('PC02', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PCO2_increase_superior_to_15_percent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis_group', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('detailled_diagnosis', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('detailled_diagnosis')
        batch_op.drop_column('diagnosis_group')
        batch_op.drop_column('PCO2_increase_superior_to_15_percent')
        batch_op.drop_column('PC02')
        batch_op.drop_column('continuous_mechanical_ventilation')
        batch_op.drop_column('six_minute_walk_distance_over_150_feet')
        batch_op.drop_column('oxygen_requirement')
        batch_op.drop_column('PA_systolic')
        batch_op.drop_column('FVC_percentage')
        batch_op.drop_column('functional_status_assistance_required')
        batch_op.drop_column('diabetes')
        batch_op.drop_column('body_mass_index')
        batch_op.drop_column('DQ')
        batch_op.drop_column('DR')
        batch_op.drop_column('B')
        batch_op.drop_column('A')
        batch_op.drop_column('ReRegistrationDate')
        batch_op.drop_column('DateTransplantation')
        batch_op.drop_column('ARFDate')
        batch_op.drop_column('EndDateDialyse')
        batch_op.drop_column('startDateDialyse')
        batch_op.drop_column('isRetransplantation')
        batch_op.drop_column('isDialyse')
        batch_op.drop_column('alpha_fetoprotein')
        batch_op.drop_column('biggest_tumor_size')
        batch_op.drop_column('tumors_number')

    # ### end Alembic commands ###
