"""Add creator_id and chat_name fields for chats

Revision ID: bbd75567551b
Revises: 1a602216162c
Create Date: 2022-02-17 23:26:22.318912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd75567551b'
down_revision = '1a602216162c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('creator_id')
        batch_op.drop_column('chat_name')

    # ### end Alembic commands ###
