"""add longitude/latitude

Revision ID: c10e830b47cf
Revises: 35c1b85ed864
Create Date: 2022-05-02 17:38:16.893394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10e830b47cf'
down_revision = '35c1b85ed864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
