"""

Revision ID: c16528f0d090
Revises: c1a3023f8e2d
Create Date: 2022-11-16 13:43:03.931748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16528f0d090'
down_revision = 'c1a3023f8e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
