"""

Revision ID: c1a3023f8e2d
Revises: 7d495cc21d28
Create Date: 2022-11-16 13:40:16.398684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a3023f8e2d'
down_revision = '7d495cc21d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
