"""Add fields for post transplantation survival

Revision ID: c66e424dfaab
Revises: b3222c8fb91d
Create Date: 2022-04-14 11:09:37.185348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66e424dfaab'
down_revision = 'b3222c8fb91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_at_transplant', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('creatinine_at_transplant', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ADL_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('PCW_over_20_mmHg', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('PCW_over_20_mmHg')
        batch_op.drop_column('ADL_required')
        batch_op.drop_column('creatinine_at_transplant')
        batch_op.drop_column('age_at_transplant')

    # ### end Alembic commands ###
