"""

Revision ID: cdb56be9d498
Revises: f2899c37b635
Create Date: 2022-11-16 10:41:20.990383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb56be9d498'
down_revision = 'f2899c37b635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
