"""

Revision ID: d1581e4f07b8
Revises: 685997781d5f
Create Date: 2022-11-29 23:53:29.501726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1581e4f07b8'
down_revision = '685997781d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_listings_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_listings_hospital_id_hospitals'), type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###
