"""

Revision ID: d233c2356204
Revises: 9f60d1fd76c6
Create Date: 2022-10-12 13:45:54.466217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd233c2356204'
down_revision = '9f60d1fd76c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_mass_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('diabetes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('functional_status_assistance_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('FVC_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PA_systolic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('oxygen_requirement', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('six_minute_walk_distance_over_150_feet', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('continuous_mechanical_ventilation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('PC02', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('PCO2_increase_superior_to_15_percent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis_group', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('detailled_diagnosis', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age_at_transplant', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creatinine_at_transplant', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ADL_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('PCW_over_20_mmHg', sa.Boolean(), nullable=True))

    with op.batch_alter_table('livers', schema=None) as batch_op:
        batch_op.alter_column('tumors_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livers', schema=None) as batch_op:
        batch_op.alter_column('tumors_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('PCW_over_20_mmHg')
        batch_op.drop_column('ADL_required')
        batch_op.drop_column('creatinine_at_transplant')
        batch_op.drop_column('age_at_transplant')
        batch_op.drop_column('detailled_diagnosis')
        batch_op.drop_column('diagnosis_group')
        batch_op.drop_column('PCO2_increase_superior_to_15_percent')
        batch_op.drop_column('PC02')
        batch_op.drop_column('continuous_mechanical_ventilation')
        batch_op.drop_column('six_minute_walk_distance_over_150_feet')
        batch_op.drop_column('oxygen_requirement')
        batch_op.drop_column('PA_systolic')
        batch_op.drop_column('FVC_percentage')
        batch_op.drop_column('functional_status_assistance_required')
        batch_op.drop_column('diabetes')
        batch_op.drop_column('body_mass_index')

    # ### end Alembic commands ###
