"""updated fields in the database w/ type

Revision ID: da08414b1e26
Revises: fa2d17c5c10d
Create Date: 2022-07-28 12:00:52.755109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da08414b1e26'
down_revision = 'fa2d17c5c10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typerdv', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('typerdv')

    # ### end Alembic commands ###
