"""

Revision ID: dd2f8fc87459
Revises: 60691e2362ef
Create Date: 2022-11-29 17:20:37.839064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2f8fc87459'
down_revision = '60691e2362ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('fk_listings_hospital_id_hospitals', type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_listings_hospital_id_hospitals', 'hospitals', ['hospital_id'], ['id'])
        batch_op.drop_column('donor')

    # ### end Alembic commands ###
