"""Add score to lungs table

Revision ID: e1c2c48132e1
Revises: 6d97c541c47a
Create Date: 2022-07-01 15:30:28.210724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c2c48132e1'
down_revision = '6d97c541c47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('PA_systolic')
        batch_op.drop_column('PCO2_increase_superior_to_15_percent')
        batch_op.drop_column('functional_status_assistance_required')
        batch_op.drop_column('continuous_mechanical_ventilation')
        batch_op.drop_column('diabetes')
        batch_op.drop_column('diagnosis_group')
        batch_op.drop_column('age_at_transplant')
        batch_op.drop_column('PCW_over_20_mmHg')
        batch_op.drop_column('body_mass_index')
        batch_op.drop_column('PC02')
        batch_op.drop_column('creatinine_at_transplant')
        batch_op.drop_column('six_minute_walk_distance_over_150_feet')
        batch_op.drop_column('FVC_percentage')
        batch_op.drop_column('ADL_required')
        batch_op.drop_column('detailled_diagnosis')
        batch_op.drop_column('oxygen_requirement')

    with op.batch_alter_table('lungs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lungs', schema=None) as batch_op:
        batch_op.drop_column('score')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oxygen_requirement', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('detailled_diagnosis', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ADL_required', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('FVC_percentage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('six_minute_walk_distance_over_150_feet', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('creatinine_at_transplant', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('PC02', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('body_mass_index', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('PCW_over_20_mmHg', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('age_at_transplant', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis_group', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('diabetes', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('continuous_mechanical_ventilation', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('functional_status_assistance_required', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('PCO2_increase_superior_to_15_percent', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('PA_systolic', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
