"""

Revision ID: f2899c37b635
Revises: 573755749d15
Create Date: 2022-11-16 10:40:54.204314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2899c37b635'
down_revision = '573755749d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heart_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CREAT', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('DCREAT', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('BILI', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('DBILI', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heart_scores', schema=None) as batch_op:
        batch_op.drop_column('DBILI')
        batch_op.drop_column('BILI')
        batch_op.drop_column('DCREAT')
        batch_op.drop_column('CREAT')

    # ### end Alembic commands ###
