"""

Revision ID: f4428fa0ae13
Revises: 2fdd13d3ddb4
Create Date: 2022-11-16 11:01:36.648749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4428fa0ae13'
down_revision = '2fdd13d3ddb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
