"""

Revision ID: f81b60980593
Revises: c6a821f7af62
Create Date: 2022-11-25 12:09:32.064492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81b60980593'
down_revision = 'c6a821f7af62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
