"""Add lungs table

Revision ID: feb4607827a9
Revises: 93fd7e6e2deb
Create Date: 2022-12-04 21:56:06.990663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb4607827a9'
down_revision = '93fd7e6e2deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
