from datetime import date
from typing import Optional, Literal
from app import db
from app.models import heart


class HeartSchema(db.Schema):
    listing_id: Optional[int]
    score: Optional[float]
    tailleD: Optional[float]
    poidsD: Optional[float]
    ABOD: Optional[str] #A/AB/B/O
    sexD: Optional[str] #
    R_D_NAI: Optional[date]
    D_INSC: Optional[date]
    MAL: Literal["Maladie valvulaire", "Maladie congenitale", "Maladie congenitale non Eisenmenger"]
    MAL2: Literal['Maladie valvulaire', 'Maladie congenitale','Maladie congenitale non Eisenmenger']
    MAL3: Literal['Maladie valvulaire', 'Maladie congenitale','Maladie congenitale non Eisenmenger']
    urgence: Optional[heart.HeartScore.URGENCE] #XPCA/XPCP1/XPCP2
    d_urgence: Optional[date]
    KXPC: Optional[str]
    XPC: Optional[int]
    DRG: Optional[str] #A/AB/B/O
    CEC: Optional[str] #A/AB/B/O
    DCEC: Optional[date]
    SIAV: Optional[str] #A/AB/B/O
    CAT: Optional[str] #A/AB/B/O
    BNP: Optional[int]
    DBNP: Optional[int]
    PROBNP: Optional[float]
    DPROBNP: Optional[date]
    DIA: Optional[str] #A/AB/B/O
    CREAT: Optional[float]
    DCREAT: Optional[date]
    BILI: Optional[float]
    DBILI: Optional[date]
    BNP_AVI: Optional[float]
    PBN_AVI: Optional[float]
    DIA_AVI: Optional[str]
    CRE_AVI: Optional[float]
    BILI_AVI: Optional[float]
    TTLGP: Optional[float]
    ICAR: Optional[float]
    F_ICAR: Optional[float]
    comp_ad_std: Optional[float]
    comp_ad_XPCA: Optional[float]
    comp_ped_std: Optional[float]
    comp_ped_XPCP: Optional[float]
    score_CCB: Optional[float]
    F1_DifAge: Optional[bool]
    F2_ABO: Optional[bool]
    F3_SC: Optional[bool]
    F4_SurvPostGRF: Optional[bool]
    score_CCP: Optional[float]
    score_NACG: Optional[float]
    D_D_NAI: Optional[date]
    D_PREL: Optional[date]

    class Config:
        orm_mode = True


class HeartCreateSchema(HeartSchema):
    listing_id: Optional[int]
    tailleD: Optional[float]
    poidsD: Optional[float]
    ABOD: Optional[str]
    sexD: Optional[str]
    R_D_NAI: Optional[date]
    D_INSC: Optional[date]
    MAL: Literal["Maladie valvulaire", "Maladie congenitale", "Maladie congenitale non Eisenmenger"]
    MAL2: Literal['Maladie valvulaire', 'Maladie congenitale','Maladie congenitale non Eisenmenger']
    MAL3: Literal['Maladie valvulaire', 'Maladie congenitale','Maladie congenitale non Eisenmenger']
    urgence: Optional[heart.HeartScore.URGENCE]
    d_urgence: Optional[date]
    KXPC: Optional[str]
    XPC: Optional[int]
    DRG: Optional[str]
    CEC: Optional[str]
    DCEC: Optional[date]
    SIAV: Optional[str]
    CAT: Optional[str]
    BNP: Optional[int]
    DBNP: Optional[int]
    PROBNP: Optional[float]
    DPROBNP: Optional[date]
    DIA: Optional[str]
    CREAT: Optional[float]
    DCREAT: Optional[date]
    BILI: Optional[float]
    DBILI: Optional[date]
    BNP_AVI: Optional[float]
    PBN_AVI: Optional[float]
    DIA_AVI: Optional[float]
    CRE_AVI: Optional[float]
    BILI_AVI: Optional[float]
    TTLGP: Optional[float]
    ICAR: Optional[float]
    F_ICAR: Optional[float]
    comp_ad_std: Optional[float]
    comp_ad_XPCA: Optional[float]
    comp_ped_std: Optional[float]
    comp_ped_XPCP: Optional[float]
    score_CCB: Optional[float]
    F1_DifAge: Optional[bool]
    F2_ABO: Optional[bool]
    F3_SC: Optional[bool]
    F4_SurvPostGRF: Optional[bool]
    score_CCP: Optional[float]
    score_NACG: Optional[float]
    D_D_NAI: Optional[date]
    D_PREL: Optional[date]
    score: Optional[float]

    

class HeartUpdateSchema(HeartSchema):
    tailleD: Optional[float]
    poidsD: Optional[float]
    ABOD: Optional[str]
    sexD: Optional[str]
    R_D_NAI: Optional[date]
    D_INSC: Optional[date]
    MAL: Literal["Maladie valvulaire", "Maladie congenitale", "Maladie congenitale non Eisenmenger"]
    MAL2: Literal['Maladie valvulaire', 'Maladie congenitale','Maladie congenitale non Eisenmenger']
    MAL3: Literal['Maladie valvulaire', 'Maladie congenitale','Maladie congenitale non Eisenmenger']
    urgence: Optional[heart.HeartScore.URGENCE]
    d_urgence: Optional[date]
    KXPC: Optional[str]
    XPC: Optional[int]
    DRG: Optional[str]
    CEC: Optional[str]
    DCEC: Optional[date]
    SIAV: Optional[str]
    CAT: Optional[str]
    BNP: Optional[int]
    DBNP: Optional[int]
    PROBNP: Optional[float]
    DPROBNP: Optional[date]
    DIA: Optional[str]
    CREAT: Optional[float]
    DCREAT: Optional[date]
    BILI: Optional[float]
    DBILI: Optional[date]
    BNP_AVI: Optional[float]
    PBN_AVI: Optional[float]
    DIA_AVI: Optional[float]
    CRE_AVI: Optional[float]
    BILI_AVI: Optional[float]
    TTLGP: Optional[float]
    ICAR: Optional[float]
    F_ICAR: Optional[float]
    comp_ad_std: Optional[float]
    comp_ad_XPCA: Optional[float]
    comp_ped_std: Optional[float]
    comp_ped_XPCP: Optional[float]
    score_CCB: Optional[float]
    F1_DifAge: Optional[bool]
    F2_ABO: Optional[bool]
    F3_SC: Optional[bool]
    F4_SurvPostGRF: Optional[bool]
    score_CCP: Optional[float]
    score_NACG: Optional[float]
    D_D_NAI: Optional[date]
    D_PREL: Optional[date]
    score: Optional[float]
    
class HeartUpdateScore(HeartSchema):
    score: float
