name: CI testing and deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose build
    - name: Run tests
      run: docker-compose run backend ./scripts/test.sh

  update:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Restart dev server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.PROD_HOST }}
          script: |
            sudo systemctl restart organia-dev
