name: Deploy dev
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  update:
    name: Deploy to dev instance
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy command on remote server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.PROD_HOST }}
          script: |
            organia-deploy dev organia-server master
