name: Deploy release
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  update:
    name: Deploy to production instance
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy command on remote server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.PROD_HOST }}
          script: |
            organia-deploy prod organia-server ${{ GITHUB_REF }}
